name: Definições de Pronto
description: Requisito mínimos para que a tarefa possa seguir com o fluxo de entrega
title: "Definiçõe de Pronto"
labels: ["Definições de Pronto | FIS-"]
projects: []
type: Informações Complementares de Teste
assignees:
  - LoriaLawrenceZ
body:
  - type: textarea
    id: def-pronto
    attributes:
      label: Definições de Pronto
      description: "Requisito mínimos para que a tarefa possa seguir com o fluxo de entrega"
      value: |
          - [ ] Caso 1
          - [ ] Caso 2
          ...
      render: bash
    validations:
      required: true
